name: AVISP
favicon: null
layout_spectrum: 0.75444
typography_spectrum: 0.49444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-66718701-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f03e00'
    - '#007fb6'
    - '#809e00'
    - '#010003'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
