name: AVISP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-66718701-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#ef5a20'
    - '#b2b3b7'
    - '#5e5e5e'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
